### ISSUE TITLE
Add "resend SMS code" logic

### ISSUE THREAD

**Issue by mre** [openpodcast/apple-automation#4]
In the open repo, we regularly run into a situation where Apple doesn't send the SMS verification code.
```
2022-11-24 12:41:47.303 | INFO     | __main__:get_cookies:49 - Got cookies response: 503
Traceback (most recent call last):
  File "/home/runner/work/open/open/apple/main.py", line 199, in <module>
    main()
  File "/home/runner/work/open/open/apple/main.py", line 113, in main
    cookies = get_cookies()
  File "/home/runner/work/open/open/apple/main.py", line 51, in get_cookies
    raise Exception(f"Failed to get cookies: {response.text}")
Exception: Failed to get cookies: Verification code not received
```

on Cloud Run we just see 

```
sign in clicked
Clicked on the phone number and waiting now...
GET429 14 B 0 ms TwilioProxy/1.1 https://apple-automation-6a7hrmyrca-ew.a.run.app/code?ToCountry=US&ToState=UT&Sms...
Verification code not received, waited 30sec
GET503 808 B 87.6 s python-requests/2.28.1 https://apple-automation.openpodcast.dev/cookies
```

It would be nice if we could try to resend the verification code if it doesn't get sent on the first try.

**Comment by woolfg** [comment]
yup, one retry would make sense after e.g. 30sec.

**Comment by mre** [comment]
#5 is an attempt to fix this
